version: "2.4"

services:
  project_server:
    build:
      context: .
      dockerfile: Dockerfile.project
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    networks:
      - my_network
    depends_on:
      - mlflow_server

  mlflow_server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - 5000:5000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge