train:
  data_dir: "data/"
  batch_size: 4
  epochs: 1

infer:
  model_path: "deceptive_review_classifier.pt"
  test_dir: "test_data/"
  output_file: "infer_results.txt"

num_classes: 2
lr: 2e-5
val_split: 0.5
random_state: 42